echo -e "[*] Instalando NVIM"
sudo apt install neovim
git clone https://github.com/folke/lazy.nvim.git ~/.local/share/nvim/lazy/lazy.nvim
mkdir -p ~/.config/nvim
echo "dmltLm9wdC50ZXJtZ3VpY29sb3JzID0gZmFsc2UgICAgICAgICAgIAp2aW0ub3B0LmJhY2tncm91bmQgPSAiZGFyayIKdmltLmNtZCgic3ludGF4IG9uIikKdmltLmNtZCgiY29sb3JzY2hlbWUgZGVmYXVsdCIpCnZpbS5vcHQubnVtYmVyID0gdHJ1ZQp2aW0ub3B0LnRhYnN0b3AgPSA0CnZpbS5vcHQuc2hpZnR3aWR0aCA9IDQKdmltLm9wdC5hdXRvaW5kZW50ID0gdHJ1ZQp2aW0ub3B0LmN1cnNvcmxpbmUgPSB0cnVlCnZpbS5vcHQuc2hvd21hdGNoID0gdHJ1ZQp2aW0ub3B0LmNsaXBib2FyZCA9ICJ1bm5hbWVkcGx1cyIKCmxvY2FsIGxhenlwYXRoID0gdmltLmZuLnN0ZHBhdGgoImRhdGEiKSAuLiAiL2xhenkvbGF6eS5udmltIgppZiBub3QgdmltLmxvb3AuZnNfc3RhdChsYXp5cGF0aCkgdGhlbgogIHZpbS5mbi5zeXN0ZW0oewogICAgImdpdCIsICJjbG9uZSIsICItLWZpbHRlcj1ibG9iOm5vbmUiLCAiaHR0cHM6Ly9naXRodWIuY29tL2ZvbGtlL2xhenkubnZpbS5naXQiLCAiLS1icmFuY2g9c3RhYmxlIiwgbGF6eXBhdGgsfSkKZW5kCnZpbS5vcHQucnRwOnByZXBlbmQobGF6eXBhdGgpCgpyZXF1aXJlKCJsYXp5Iikuc2V0dXAoewogIHsgIm52aW0tdHJlZS9udmltLXRyZWUubHVhIiwKICAgIGRlcGVuZGVuY2llcyA9IHsgIm52aW0tdHJlZS9udmltLXdlYi1kZXZpY29ucyIgfSwKICAgIGNvbmZpZyA9IGZ1bmN0aW9uKCkKICAgICAgcmVxdWlyZSgibnZpbS10cmVlIikuc2V0dXAoe30pCiAgICAgIHZpbS5rZXltYXAuc2V0KCJuIiwgIjxsZWFkZXI+ZSIsICI6TnZpbVRyZWVUb2dnbGU8Q1I+IikKICAgIGVuZCwgIH0sCiAgeyAiaHJzaDd0aC9udmltLWNtcCIsICBkZXBlbmRlbmNpZXMgPSB7ICJocnNoN3RoL2NtcC1idWZmZXIiLCAgfSwKICAgIGNvbmZpZyA9IGZ1bmN0aW9uKCkKICAgICAgbG9jYWwgY21wID0gcmVxdWlyZSgiY21wIikKICAgICAgY21wLnNldHVwKHsgc291cmNlcyA9IHsgeyBuYW1lID0gImJ1ZmZlciIgfSwgfSwKICAgICAgICBtYXBwaW5nID0gewogICAgICAgICAgWyI8VGFiPiJdID0gY21wLm1hcHBpbmcuc2VsZWN0X25leHRfaXRlbSgpLAogICAgICAgICAgWyI8Uy1UYWI+Il0gPSBjbXAubWFwcGluZy5zZWxlY3RfcHJldl9pdGVtKCksCiAgICAgICAgICBbIjxDUj4iXSA9IGNtcC5tYXBwaW5nLmNvbmZpcm0oeyBzZWxlY3QgPSB0cnVlIH0pLCAgfSwKICAgICAgfSkgIGVuZCwgfSwKICB7ICJ0cG9wZS92aW0tc3Vycm91bmQiIH0sCiAgeyAidHBvcGUvdmltLWNvbW1lbnRhcnkiIH0sCiAgeyAidHBvcGUvdmltLXJlcGVhdCIgfSwKICB7ICJ3aW5kd3AvbnZpbS1hdXRvcGFpcnMiLCBjb25maWcgPSBmdW5jdGlvbigpCiAgICAgIHJlcXVpcmUoIm52aW0tYXV0b3BhaXJzIikuc2V0dXAoe30pICBlbmQsIH0sCiAgeyAiYWx2YW4vdmltLWNsb3NldGFnIiwgZnQgPSB7ICJodG1sIiwgInhtbCIsICJqc3giLCAidHN4IiB9LCB9ICB9KSAgICAgICAgICAgICAK" | base64 -d > ~/.config/nvim/init.lua

echo -e "[*] Instalando herramientas"
sudo apt install ripgrep fd-find bat fzf 
echo "YWxpYXMgY2F0PS91c3IvYmluL2JhdGNhdApzb3VyY2UgPChmemYgLS16c2gpCmV2YWwgIiQoem94aWRlIGluaXQgenNoIC0tY21kIHopIgphbGlhcyBscz0iZXhhIC0taWNvbnMiCmFsaWFzIGZkPSJmZGZpbmQiCmFsaWFzIHRyZWU9ImV4YSAtLWljb25zIC0tdHJlZSIKYWxpYXMgY2Q9Inoi" | base64 -d >> ~/.zshrc


echo -e "[*] Instalando fuente"
mkdir -p /usr/local/share/fonts/HermitNerdFont; cd /tmp
wget -O Hermit.zip "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hermit.zip"
sudo unzip /tmp/Hermit.zip -d /usr/local/share/fonts/HermitNerdFont
fc-cache -fv

echo -e "[*] Instalando emulador de terminal"
sudo apt install alacritty 
echo "W2NvbG9ycy5icmlnaHRdICAgICAgICAgIApibGFjayA9ICIweDU1NTc1MyIgICAgICAgCmJsdWUgPSAiMHg3MjlmY2YiICAgICAgICAKY3lhbiA9ICIweDM0ZTJlMiIgICAgICAgIApncmVlbiA9ICIweDhhZTIzNCIgICAgICAgCm1hZ2VudGEgPSAiMHhhZDdmYTgiICAgICAKcmVkID0gIjB4ZWYyOTI5IiAgICAgICAgIAp3aGl0ZSA9ICIweGVlZWVlYyIgICAgICAgCnllbGxvdyA9ICIweGZjZTk0ZiIgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgIApbY29sb3JzLm5vcm1hbF0gICAgICAgICAgCmJsYWNrID0gIjB4MmUzNDM2IiAgICAgICAKYmx1ZSA9ICIweDM0NjVhNCIgICAgICAgIApjeWFuID0gIjB4MDY5ODlhIiAgICAgICAgCmdyZWVuID0gIjB4NGU5YTA2IiAgICAgICAKbWFnZW50YSA9ICIweDc1NTA3YiIgICAgICAKcmVkID0gIjB4Y2MwMDAwIiAgICAgICAgCndoaXRlID0gIjB4ZDNkN2NmIiAgICAgICAgICAgCnllbGxvdyA9ICIweGM0YTAwMCIgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgIApbY29sb3JzLnByaW1hcnldICAgICAgICAgCmJhY2tncm91bmQgPSAiMHgwMDAwMDAiICAKZm9yZWdyb3VuZCA9ICIweGQzZDdjZiIgCgpbZm9udF0Kc2l6ZSA9IDE2CgpbZm9udC5ib2xkXQpmYW1pbHkgPSAiSHVybWl0IE5lcmQgRm9udCIKc3R5bGUgPSAiQm9sZCIKCltmb250LmJvbGRfaXRhbGljXQpmYW1pbHkgPSAiSHVybWl0IE5lcmQgRm9udCIKc3R5bGUgPSAiQm9sZCBJdGFsaWMiCgpbZm9udC5pdGFsaWNdCmZhbWlseSA9ICJIdXJtaXQgTmVyZCBGb250IgpzdHlsZSA9ICJJdGFsaWMiCgpbZm9udC5ub3JtYWxdCmZhbWlseSA9ICJIdXJtaXQgTmVyZCBGb250IgpzdHlsZSA9ICJSZWd1bGFyIgoKW3dpbmRvd10Kb3BhY2l0eSA9IDAuOAoKW3dpbmRvdy5wYWRkaW5nXQp4ID0gNQp5ID0gMg==" | base64 -d > /etc/xdg/alacritty/alacritty.toml

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
