set -g default-terminal "tmux-256color"                                                           [0/12]
set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g status-left-style "bg=#a6e3a1,fg=#1e1e2e"
set -g status-right-style "bg=#a6e3a1,fg=#1e1e2e"
set -g automatic-rename on
set -g allow-rename off
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g status-left-length 100
set -g status-right-length 100
set -g status-right '   #{cpu_percentage} |   #(ip route get 1.1.1.1 | awk "{print \$7; exit}") |  #(
ifconfig | grep tun0 -A 1 | grep inet | awk "{print \$2; exit}") '
run '~/.tmux/plugins/tmux/catppuccin.tmux'
run '~/.tmux/plugins/tpm/tpm'
set -g window-status-current-format '#[bg=#cdd6f4,fg=#1e1e2e,bold] #I #W '
set -g window-status-format ' #I #W '
set -g status-left "   "
